name: ci

on:
  push:
    branches: [main]
    tags: ["**"]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  python:
    permissions:
      contents: read
    strategy:
      matrix:
        model: [mf, seq, seq_embedded]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      PROJECT_NAME: xfmr_rec
      UV_LOCKED: "1"
      UV_NO_SYNC: "1"
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7

      - id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6

      - run: uv sync && uv pip list

      - if: ${{ success() || failure() }}
        run: uv run ${{ matrix.model }}_train fit --print_config

      - if: ${{ success() || failure() }}
        run: |
          uv run ${{ matrix.model }}_train fit \
            --trainer.limit_train_batches 1 \
            --trainer.limit_val_batches 1 \
            --data.config.num_workers 0

      - if: ${{ success() || failure() }}
        run: uv run ${{ matrix.model }}_deploy

      - if: ${{ failure() }}
        run: uv run python -m "${PROJECT_NAME}.${{ matrix.model }}.trainer"

      - if: ${{ failure() }}
        run: uv run python -m "${PROJECT_NAME}.${{ matrix.model }}.data"

      - if: ${{ failure() }}
        run: uv run data

  docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    env:
      GHCR_IMAGE_NAME: ghcr.io/${{ github.repository }}
      PROJECT_NAME: xfmr_rec
      DOCKER_RUN_CMD: >-
        docker run
          --env "HF_HOME=/tmp/huggingface"
          --volume /tmp/huggingface:/tmp/huggingface
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          sparse-checkout: uv.lock

      - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          cache-from: ${{ env.GHCR_IMAGE_NAME }}:cache
          load: true

      - if: ${{ success() || failure() }}
        run: ${DOCKER_RUN_CMD} "${IMAGE_ID}" uv pip list
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ success() || failure() }}
        run: |
          ${DOCKER_RUN_CMD} "${IMAGE_ID}" \
            uv run seq_train fit --print_config
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ success() || failure() }}
        run: |
          ${DOCKER_RUN_CMD} "${IMAGE_ID}" \
            uv run seq_train fit \
            --trainer.limit_train_batches 1 \
            --trainer.limit_val_batches 1 \
            --data.config.num_workers 0
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ success() || failure() }}
        run: ${DOCKER_RUN_CMD} "${IMAGE_ID}" uv run seq_deploy
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ failure() }}
        run: |
          ${DOCKER_RUN_CMD} "${IMAGE_ID}" \
            python -m "${PROJECT_NAME}.seq.trainer"
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ failure() }}
        run: |
          ${DOCKER_RUN_CMD} "${IMAGE_ID}" \
            python -m "${PROJECT_NAME}.seq.data"
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - if: ${{ failure() }}
        run: ${DOCKER_RUN_CMD} "${IMAGE_ID}" uv run data
        env:
          IMAGE_ID: ${{ steps.build.outputs.imageid }}

      - id: docker_metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.GHCR_IMAGE_NAME }}

      - if: ${{ github.event_name == 'push' || github.ref_name == github.event.repository.default_branch }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - if: ${{ github.event_name == 'push' || github.ref_name == github.event.repository.default_branch }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          cache-from: ${{ env.GHCR_IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.GHCR_IMAGE_NAME }}:cache,mode=max
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          annotations: ${{ steps.docker_metadata.outputs.annotations }}
          push: ${{ github.event_name == 'push' || github.ref_name == github.event.repository.default_branch }}
